"use client";

import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { format, parseISO } from "date-fns";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { ArrowLeft, ArrowRight, CalendarClock, CalendarDays, CheckCircle2, Clock3, MailSearch, RotateCcw, Scissors, Star, UserRound, XCircle } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { PageHero, EmptyState } from "@/src/components/shared";
import { barbers, chairs, services } from "@/src/data/catalog";
import { useAppStore } from "@/src/store/app-store";
import { canModifyBooking, formatCurrency } from "@/src/utils/booking";
import type { Booking } from "@/src/types/domain";

export function MyBookingsPage() {
  const { bookings, userId } = useAppStore();
  const [guestEmail, setGuestEmail] = useState(""); const [guestCode, setGuestCode] = useState(""); const [guestMatch, setGuestMatch] = useState<Booking | null>(null); const [searched, setSearched] = useState(false);
  const mine = useMemo(() => bookings.filter((booking) => userId ? booking.customerId === userId : false), [bookings, userId]);
  const groups = { upcoming: mine.filter((booking) => booking.status === "confirmed" && parseISO(booking.endAt) > new Date()), completed: mine.filter((booking) => booking.status === "completed" || (booking.status === "confirmed" && parseISO(booking.endAt) <= new Date())), cancelled: mine.filter((booking) => ["cancelled", "rescheduled"].includes(booking.status)) };
  const searchGuest = (event: React.FormEvent) => { event.preventDefault(); const found = bookings.find((booking) => booking.confirmationNumber.toLowerCase() === guestCode.trim().toLowerCase() && booking.customer.email.toLowerCase() === guestEmail.trim().toLowerCase()); setGuestMatch(found || null); setSearched(true); };
  return <><PageHero eyebrow="Appointment desk" title="Your bookings, in one place." copy="Review upcoming visits, make a change, or find a guest booking with its confirmation number." /><section className="section-space page-shell bookings-page">{userId ? <Tabs defaultValue="upcoming"><TabsList className="booking-tabs"><TabsTrigger value="upcoming">Upcoming <span>{groups.upcoming.length}</span></TabsTrigger><TabsTrigger value="completed">Completed <span>{groups.completed.length}</span></TabsTrigger><TabsTrigger value="cancelled">Past changes <span>{groups.cancelled.length}</span></TabsTrigger></TabsList><TabsContent value="upcoming"><BookingList bookings={groups.upcoming} empty="No upcoming appointments" /></TabsContent><TabsContent value="completed"><BookingList bookings={groups.completed} empty="No completed appointments yet" /></TabsContent><TabsContent value="cancelled"><BookingList bookings={groups.cancelled} empty="No cancelled or rescheduled appointments" /></TabsContent></Tabs> : <div className="guest-booking-layout"><div><span className="eyebrow">Guest booking</span><h2>Find your appointment.</h2><p>Enter the email used to book and the confirmation number shown after checkout.</p><form onSubmit={searchGuest} className="guest-search"><div className="field"><Label htmlFor="guest-email">Email</Label><Input id="guest-email" type="email" value={guestEmail} onChange={(event) => setGuestEmail(event.target.value)} required /></div><div className="field"><Label htmlFor="guest-code">Confirmation number</Label><Input id="guest-code" value={guestCode} onChange={(event) => setGuestCode(event.target.value)} placeholder="GC-XXXXXX" required /></div><Button><MailSearch /> Find booking</Button></form><p className="account-prompt">Have an account? <Link to="/login?returnTo=/my-bookings">Sign in to see your history</Link></p></div><div className="guest-result">{guestMatch ? <BookingCard booking={guestMatch} /> : searched ? <EmptyState title="No booking matched" copy="Check the confirmation number and email, then try again." /> : <div className="lookup-placeholder"><MailSearch /><h3>Your appointment will appear here</h3><p>Try the seeded demo booking: GC-DEMO24 and demo@gentlemanschair.example</p></div>}</div></div>}</section></>;
}

function BookingList({ bookings, empty }: { bookings: Booking[]; empty: string }) {
  return bookings.length ? <div className="booking-list">{bookings.map((booking) => <BookingCard key={booking.id} booking={booking} />)}</div> : <EmptyState title={empty} copy="When a booking belongs here, it will appear automatically." action={<Button asChild><Link to="/book/service">Book an appointment</Link></Button>} />;
}

function BookingCard({ booking }: { booking: Booking }) {
  const service = services.find((item) => item.id === booking.serviceId); const barber = barbers.find((item) => item.id === booking.barberId); const chair = chairs.find((item) => item.id === booking.chairId); const start = parseISO(booking.startAt);
  return <article className="booking-card"><div className="booking-date-block"><small>{format(start, "MMM")}</small><strong>{format(start, "d")}</strong><span>{format(start, "EEE")}</span></div><div className="booking-card-main"><div className="booking-card-title"><div><span className={`status-badge status-${booking.status}`}>{booking.status}</span><h3>{service?.name}</h3><p>{booking.confirmationNumber}</p></div><strong>{formatCurrency(booking.total)}</strong></div><div className="booking-facts"><span><Clock3 /> {format(start, "HH:mm")} · {service?.duration} min</span><span><UserRound /> {barber?.name}</span><span><Scissors /> {chair?.name}</span></div><div className="card-actions"><Button variant="ghost" asChild><Link to={`/my-bookings/${booking.id}`}>View details</Link></Button>{booking.status === "completed" ? <ReviewDialog booking={booking} /> : null}{booking.status === "confirmed" ? <Button variant="outline" asChild><Link to={`/my-bookings/${booking.id}`}>Manage <ArrowRight /></Link></Button> : <Button variant="outline" asChild><Link to={`/book/service?service=${booking.serviceId}`}>Book again</Link></Button>}</div></div></article>;
}

export function BookingDetailPage({ id }: { id: string }) {
  const navigate = useNavigate();
  const { bookings, cancelBooking, updateDraft } = useAppStore(); const booking = bookings.find((item) => item.id === id);
  if (!booking) return <div className="not-found page-shell"><span>404</span><h1>Booking not found.</h1><p>That appointment may not exist in this browser.</p><Button asChild><Link to="/my-bookings">Back to My Bookings</Link></Button></div>;
  const service = services.find((item) => item.id === booking.serviceId)!; const barber = barbers.find((item) => item.id === booking.barberId)!; const chair = chairs.find((item) => item.id === booking.chairId)!; const modifiable = canModifyBooking(booking); const reviewed = useAppStore.getState().reviews.some((review) => review.bookingId === booking.id);
  const reschedule = () => { const start = parseISO(booking.startAt); updateDraft({ serviceId: booking.serviceId, barberPreference: booking.barberId, assignedBarberId: booking.barberId, date: format(start, "yyyy-MM-dd"), time: format(start, "HH:mm"), chairId: booking.chairId, customer: booking.customer, originalBookingId: booking.id }); navigate("/book/service"); };
  return <section className="booking-detail page-shell"><Link to="/my-bookings" className="back-link"><ArrowLeft /> My bookings</Link><div className="booking-detail-head"><div><span className={`status-badge status-${booking.status}`}>{booking.status}</span><h1>{service.name}</h1><p>Confirmation <strong>{booking.confirmationNumber}</strong></p></div><div className="detail-total"><small>Total</small><strong>{formatCurrency(booking.total)}</strong></div></div><div className="booking-detail-grid"><div className="appointment-panel"><span className="eyebrow">Appointment details</span><DetailRow icon={<CalendarDays />} label="Date" value={format(parseISO(booking.startAt), "EEEE, d MMMM yyyy")} /><DetailRow icon={<Clock3 />} label="Time" value={`${format(parseISO(booking.startAt), "HH:mm")} – ${format(parseISO(booking.endAt), "HH:mm")} · ${service.duration} min`} /><DetailRow icon={<UserRound />} label="Barber" value={`${barber.name} · ${barber.title}`} /><DetailRow icon={<Scissors />} label="Station" value={`${chair.name} · ${chair.description}`} /></div><div className="customer-panel"><span className="eyebrow">Customer</span><h2>{booking.customer.fullName}</h2><p>{booking.customer.email}<br />{booking.customer.phone}</p>{booking.customer.notes ? <blockquote>{booking.customer.notes}</blockquote> : null}<div className="price-lines"><p><span>Service</span><strong>{formatCurrency(booking.subtotal)}</strong></p><p><span>Discount</span><strong>{booking.discount ? `−${formatCurrency(booking.discount)}` : "—"}</strong></p><p><span>Total</span><strong>{formatCurrency(booking.total)}</strong></p></div></div></div>
    {booking.status === "confirmed" ? <div className="manage-panel"><div><span className="eyebrow">Manage appointment</span><h2>Plans changed?</h2><p>{modifiable ? "You can reschedule or cancel until two hours before your appointment." : "This appointment is inside the two-hour change window. Please call the shop for assistance."}</p></div><div><Button variant="outline" onClick={reschedule} disabled={!modifiable}><RotateCcw /> Reschedule</Button><CancelDialog booking={booking} disabled={!modifiable} onCancel={() => { cancelBooking(booking.id); toast.success("Appointment cancelled. The barber and chair are available again."); }} /></div></div> : booking.status === "completed" && !reviewed ? <div className="manage-panel"><div><span className="eyebrow">Completed visit</span><h2>How was your appointment?</h2><p>Your review will stay connected to this service and barber.</p></div><ReviewDialog booking={booking} /></div> : null}
  </section>;
}

function CancelDialog({ booking, disabled, onCancel }: { booking: Booking; disabled: boolean; onCancel: () => void }) {
  const service = services.find((item) => item.id === booking.serviceId); const barber = barbers.find((item) => item.id === booking.barberId);
  return <AlertDialog><AlertDialogTrigger asChild><Button variant="destructive" disabled={disabled}><XCircle /> Cancel appointment</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancel this appointment?</AlertDialogTitle><AlertDialogDescription>{service?.name} with {barber?.name} on {format(parseISO(booking.startAt), "EEEE, d MMMM 'at' HH:mm")}. This releases the barber and chair immediately.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep appointment</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={onCancel}>Cancel appointment</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>;
}

const reviewSchema = z.object({ rating: z.coerce.number().min(1).max(5), barberRating: z.coerce.number().min(1).max(5).optional(), body: z.string().trim().min(10, "Write at least 10 characters").max(600) });
type ReviewValues = z.infer<typeof reviewSchema>;
function ReviewDialog({ booking }: { booking: Booking }) {
  const { addReview, reviews } = useAppStore(); const [open, setOpen] = useState(false); const existing = reviews.some((review) => review.bookingId === booking.id);
  const { register, handleSubmit, reset, formState: { errors } } = useForm<ReviewValues>({ resolver: zodResolver(reviewSchema), defaultValues: { rating: 5, barberRating: 5, body: "" } });
  const submit = (values: ReviewValues) => { addReview({ id: crypto.randomUUID(), bookingId: booking.id, customerName: booking.customer.fullName, barberId: booking.barberId, serviceId: booking.serviceId, rating: values.rating, barberRating: values.barberRating, body: values.body.trim(), createdAt: new Date().toISOString() }); toast.success("Thank you. Your review is now published."); setOpen(false); reset(); };
  if (existing) return <span className="reviewed-label"><CheckCircle2 /> Reviewed</span>;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Star /> Leave review</Button></DialogTrigger><DialogContent className="review-dialog"><DialogHeader><DialogTitle>Review your appointment</DialogTitle><DialogDescription>Only completed bookings can be reviewed, once per visit.</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)} className="form-stack"><div className="form-two"><div className="field"><Label htmlFor={`rating-${booking.id}`}>Overall rating</Label><Input id={`rating-${booking.id}`} type="number" min={1} max={5} {...register("rating")} />{errors.rating ? <p className="field-error">{errors.rating.message}</p> : null}</div><div className="field"><Label htmlFor={`barber-rating-${booking.id}`}>Barber rating</Label><Input id={`barber-rating-${booking.id}`} type="number" min={1} max={5} {...register("barberRating")} /></div></div><div className="field"><Label htmlFor={`review-${booking.id}`}>Your review</Label><Textarea id={`review-${booking.id}`} {...register("body")} placeholder="Tell future guests what stood out…" />{errors.body ? <p className="field-error">{errors.body.message}</p> : null}</div><Button>Publish review</Button></form></DialogContent></Dialog>;
}

function DetailRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="detail-row"><span>{icon}</span><p><small>{label}</small><strong>{value}</strong></p></div>; }
