"use client";

import { Link } from "react-router-dom";
import { ArrowRight, Award, CalendarCheck2, Clock3, MapPin, Scissors, ShieldCheck, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { barbers, reviews, services } from "@/src/data/catalog";
import { BarberCard, ReviewCard, SectionHeading, ServiceCard } from "@/src/components/shared";
import { BUSINESS, HOURS_LABELS } from "@/src/config/business";

export function HomePage() {
  return <>
    <section className="hero-section"><div className="hero-grain" aria-hidden="true"/><div className="page-shell hero-grid"><div className="hero-copy reveal"><span className="eyebrow"><span className="line" /> Est. Dubai · 2016</span><h1>Precision cuts.<br /><em>Timeless style.</em></h1><p>A modern grooming house for men who appreciate quiet confidence, expert hands, and time well spent.</p><div className="hero-actions"><Button asChild size="lg"><Link to="/book/service">Reserve your chair <ArrowRight /></Link></Button><Button asChild size="lg" variant="outline"><Link to="/services">Explore services</Link></Button></div><div className="trust-row"><div><strong>4.9</strong><span>Guest rating</span></div><div><strong>5</strong><span>Master barbers</span></div><div><strong>8+</strong><span>Years in Dubai</span></div></div></div>
      <div className="hero-visual" aria-label="Premium barbering at The Gentleman's Chair"><div className="hero-ring ring-one"/><div className="hero-ring ring-two"/><div className="image-plane"><img src="https://www.clearpath-digital.com/assets/case-barber-DkGGAgdD.jpg" alt="Warm, premium barbershop interior with leather chairs" /><div className="image-shine" /></div><div className="floating-card fc-top"><Scissors /><span><small>Next opening</small><strong>Today · 18:30</strong></span></div><div className="floating-card fc-bottom"><CalendarCheck2 /><span><small>Instant confirmation</small><strong>Book in under 2 minutes</strong></span></div><div className="visual-monogram" aria-hidden="true">GC</div></div>
    </div><div className="hero-scroll" aria-hidden="true"><span /> Scroll to discover</div></section>

    <section className="craft-strip"><div className="page-shell craft-grid"><div><Award /><span><strong>Master craftsmanship</strong>Every detail, considered.</span></div><div><Clock3 /><span><strong>Your time, respected</strong>Appointments that run on time.</span></div><div><ShieldCheck /><span><strong>Refined standards</strong>Clean tools. Premium products.</span></div></div></section>

    <section className="section-space about-section"><div className="page-shell about-grid"><div className="about-visual"><div className="about-frame"><img src="https://barbersaas.com.br/assets/hero-barbershop-BSTGMNf_.jpg" alt="Barbers delivering a precise haircut in a warm, refined studio" loading="lazy" /></div><span className="about-stamp"><strong>8</strong> years of craft</span></div><div><SectionHeading eyebrow="Our philosophy" title="Grooming without the rush." copy="We built The Gentleman's Chair around one belief: a great appointment should feel as considered as the final cut." /><div className="about-points"><div><span>01</span><div><h3>Listen first</h3><p>Every service begins with a real consultation—your routine, your texture, your style.</p></div></div><div><span>02</span><div><h3>Craft with intent</h3><p>Modern technique meets traditional discipline, from the first section to the final detail.</p></div></div><div><span>03</span><div><h3>Leave sharper</h3><p>Practical styling advice helps your look hold long after you leave the chair.</p></div></div></div><Button asChild variant="outline"><Link to="/barbers">Meet the team <ArrowRight /></Link></Button></div></div></section>

    <section className="section-space services-section"><div className="page-shell"><div className="section-top"><SectionHeading eyebrow="The service menu" title="Essential rituals, elevated." copy="Straightforward services, exceptional execution. Every price and duration is clear before you book." /><Button asChild variant="ghost"><Link to="/services">View all services <ArrowRight /></Link></Button></div><div className="service-grid">{services.slice(0, 3).map((service) => <ServiceCard service={service} key={service.id} />)}</div></div></section>

    <section className="section-space team-section"><div className="page-shell"><SectionHeading eyebrow="The collective" title="Find your barber." copy="Five distinct specialists. One exacting standard." align="center" /><div className="barber-grid">{barbers.slice(0, 3).map((barber) => <BarberCard barber={barber} key={barber.id} />)}</div><div className="center-action"><Button asChild variant="outline"><Link to="/barbers">View every barber <ArrowRight /></Link></Button></div></div></section>

    <section className="section-space testimonials-section"><div className="page-shell"><SectionHeading eyebrow="Guest notes" title="The feeling after a great cut." /><div className="review-grid">{reviews.slice(0, 3).map((review) => <ReviewCard review={review} key={review.id} />)}</div></div></section>

    <section className="visit-section"><div className="page-shell visit-grid"><div className="map-art"><div className="map-grid"/><div className="map-route"/><span className="map-pin"><MapPin /></span><div className="map-label"><strong>The Gentleman's Chair</strong><small>Al Wasl · Dubai</small></div></div><div className="visit-copy"><span className="eyebrow">Visit the house</span><h2>Your chair is waiting.</h2><p>{BUSINESS.address}</p><div className="hours-list">{HOURS_LABELS.map(([day, value]) => <div key={day}><span>{day}</span><strong>{value}</strong></div>)}</div><div className="hero-actions"><Button asChild><Link to="/book/service">Book an appointment <ArrowRight /></Link></Button><Button variant="outline" asChild><a href={`tel:${BUSINESS.phone}`}>Call the shop</a></Button></div></div></div></section>
  </>;
}
